---
- name: install tar
  become: yes
  apt:
    name: tar
    state: latest
    update_cache: yes

- name: Add nodejs
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash 
    sudo apt-get install -y nodejs
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: copy built backend files
  become: yes
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Ensuring built backend files is copied"
  shell: |
    sleep 15

- name: Extract backend files
  shell: |
    cd /home/ubuntu
    tar -xzvf artifact.tar.gz


- name: pm2 start
  shell: |    
    npm i
    pm2 stop default
    pm2 start npm -- start