- name: "install node exporter."
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/node_exporter-0.17.0.linux-amd64/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0777'
    
- name: "add node exporter configuration."
  become: true
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: "enable node_exporter service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
    enabled: yes

# add code for postgress DB
- name: "install dependances for project"
  become: true
  shell: |
    sudo apt-get -y update
    sudo apt-get -y install ca-certificates curl gnupg lsb-release

    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get -y update
    sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
    sudo docker run --name some-postgres -e POSTGRES_PASSWORD=123456789 -d -p 5432:5432 postgress
